eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance.:
      preferIpAddress: true

server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    enabled: false
    sampler.percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zkNodes: 127.0.0.1:2181
zipkin:
  storage:
    type: elasticsearch
    StorageComponent: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: localhost:9200
management:
  security:
    enabled: false
