server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    metadata-map:
          user.name: admin
          user.password: admin
#    health-check-url-path: /actuator/health
#    home-page-url-path: /actuator
#    status-page-url-path: /actuator/info
  client:
    registerWithEureka: false
    fetchRegistry: false
#    service-url:
#      defaultZone: http://localhost:8761/eureka